## Where Do People Drink The Most Beer, Wine And Spirits?

<img src="https://s1.qwant.com/thumbr/0x0/3/f/a2d61eb9aa851a55e62456389bde7986e358da62a08b5c5ac98aaa851447dc/alcoholconsumption.gif?u=http%3A%2F%2F4.bp.blogspot.com%2F-0u5Sk_omAEE%2FTV3XZtyPQ1I%2FAAAAAAAAArc%2FyVlSiUp6aTU%2Fs1600%2Falcoholconsumption.gif&q=0&b=1&p=0&a=1">

The dataset for this analysis is from this post in [FiveThirtyEight](https://fivethirtyeight.com/features/dear-mona-followup-where-do-people-drink-the-most-beer-wine-and-spirits/)

Data: https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

url = 'https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv'
alchohol_drink = pd.read_csv(url)
alchohol_drink.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9

## Problem 1
Convert the following data into tidy format with the headers `country`, `drink` and `servings`. Drop the column `total_litres_of_pure_alcohol`

In [2]:
alchohol_tidy = pd.melt(
    alchohol_drink,
    id_vars=['country'],
    value_vars=['beer_servings', 'spirit_servings', 'wine_servings'],
    var_name='drink',
    value_name='servings'
)
alchohol_tidy.head(250)

               country            drink  servings
0          Afghanistan    beer_servings         0
1              Albania    beer_servings        89
2              Algeria    beer_servings        25
3              Andorra    beer_servings       245
4               Angola    beer_servings       217
..                 ...              ...       ...
245            Ecuador  spirit_servings        74
246              Egypt  spirit_servings         4
247        El Salvador  spirit_servings        69
248  Equatorial Guinea  spirit_servings         0
249            Eritrea  spirit_servings         0

[250 rows x 3 columns]

## Problem 2
Remove `"_servings"` from the data in the tidy dataframe in Problem 1. Who drinks the most beer, wine and spirits? Create three categorical plots of your choice to illustrate the top 10 countries that drink the most wine, beer or spirits.

In [4]:
# Remove suffix
alchohol_tidy['drink'] = alchohol_tidy['drink'].str.replace('_servings', '', regex=False)

       country drink  servings
0  Afghanistan  beer         0
1      Albania  beer        89
2      Algeria  beer        25
3      Andorra  beer       245
4       Angola  beer       217

In [5]:
alchohol_wide = alchohol_tidy.pivot_table(index='country', columns='drink', values='servings')
alchohol_wide.head()

drink         beer  spirit   wine
country
Afghanistan    0.0     0.0    0.0
Albania       89.0   132.0   54.0
Algeria       25.0     0.0   14.0
Andorra      245.0   138.0  312.0
Angola       217.0    57.0   45.0

## Problem 3
Create a wide dataframe using `pivot_table` with the tidy dataframe from Problem 2

In [13]:
alchohol_wide = alchohol_tidy.pivot_table(
    index='country',
    columns='drink',
    values='servings'
)
alchohol_wide.head()

drink         beer  spirit   wine
country
Afghanistan    0.0     0.0    0.0
Albania       89.0   132.0   54.0
Algeria       25.0     0.0   14.0
Andorra      245.0   138.0  312.0
Angola       217.0    57.0   45.0